### ISSUE TITLE
请添加github帐号登录功能.

### ISSUE THREAD

**Issue by wsdjeg** [rust-cn/rust_lang_cn#11]
@liyuan462 
你好, 现在各种社区非常多, 如果为每一个社区去注册一个帐号, 那么将有很多帐号需要记忆, 我觉得ruby china 以及 gitter.im 的登录模式就非常的不错, 使用github的帐号登录.

**Comment by chpengzh** [comment]
https://developer.github.com/v3/oauth/

**Comment by liyuan462** [comment]
嗯，将列入todo中

**Comment by wsdjeg** [comment]
还有一个rustcc组织，貌似有个牛人呢😊，不过他们没搞社区

**Comment by liyuan462** [comment]
嗯，rustcc下面有几个不错的repo

**Comment by liyuan462** [comment]
已经支持用GitHub账号登录了 https://github.com/rust-cn/rust_lang_cn/commit/633509335ce55361618fc5e0be7491f5fae3bf92

**Comment by wsdjeg** [comment]
谢谢

**Comment by liyuan462** [comment]
@wsdjeg 不客气，提issue是欢迎的
