### ISSUE TITLE
希望能够增加 License

### ISSUE THREAD

**Issue by momosaki** [rust-cn/rust_lang_cn#24]
最近有些希望使用 Rust 编写网站程序，如果可以的话，希望能够基于本项目的基础开始。
但是因为本项目没有指明具体的协议，不能贸然作出决定。
希望能为本项目添加适当的开源协议。非常感谢！

**Comment by liyuan462** [comment]
开源协议已添加（MIT），欢迎进行二次开发

**Comment by momosaki** [comment]
谢谢 <3
