### ISSUE TITLE
登录会话问题

### ISSUE THREAD

**Issue by duobei** [rust-cn/rust_lang_cn#26]
场景：
1、起初未登录 rust 论坛，打开论坛的几个页面
2、新开标签页登录 rust 论坛
3、刷新未登录前打开的页面，页面还是未登录

可能就是一个简单的会话问题，我看下能不能有时间改下

**Comment by liyuan462** [comment]
我自己的浏览器上测是没问题的，你再确认下，看是不是浏览器兼容性之类的问题。另外，欢迎提交pull request!

**Comment by duobei** [comment]
我确认了下，是没问题的，谢谢。
