### ISSUE TITLE
markdown table 显示不正确

### ISSUE THREAD

**Issue by MiYogurt** [rust-cn/rust_lang_cn#3]
在 markdown 编辑器里面的预览可以正常显示。
提交文章之后，就无法显示正确了。

**Comment by liyuan462** [comment]
关于markdown table 语法，目前的common mark标准还不支持，只能用raw html来写
http://spec.commonmark.org/0.25/

**Comment by liyuan462** [comment]
暂时先关了，看以后rust pulldown_cmark会不会支持
