### ISSUE TITLE
增加表情支持

### ISSUE THREAD

**Issue by MiYogurt** [rust-cn/rust_lang_cn#5]
最好数据库编码支持这样的👿  emoji 表情。
外置一些这样的表情，就更棒了！！
![image](https://cloud.githubusercontent.com/assets/10082395/15884949/48941270-2d86-11e6-85f7-54a0bb39fac2.png)

**Comment by liyuan462** [comment]
数据库编码已经支持表情了，先关掉了，外置表情是后话了
