### ISSUE TITLE
RESTful API

### ISSUE THREAD

**Issue by zanjs** [rust-cn/rust_lang_cn#6]
look forward to RESTful API

**Comment by liyuan462** [comment]
你想用API来干嘛呢

**Comment by MiYogurt** [comment]
@zanjs 想来为我们做一个 React 版本的前端么，我看你 React 技术很赞！假如是的话，非常欢迎。😄  设计图在 rust-cn/rust-china-web-design

**Comment by zanjs** [comment]
恩是的 想做 React 版本的 😄

**Comment by MiYogurt** [comment]
@zanjs 那就把这项重大任务交给你了。(_^__^_) 嘻嘻，我今天刚开了一个vue的坑，刚写了个静态的nav。下周我就要忙了。i trust you！ rest api 没做好之前 用 mock.js 生成api写测试。欢迎，欢迎~哈哈！

**Comment by liyuan462** [comment]
@zanjs @MiYogurt 网页版前端大家可以尝试新技术，不过像直接换React版可能算比较激进和根本性的改变，而且可能也涉及到后端返回数据的变化，可以试着玩一下，但正式环境还是会偏向保守。目前阶段最急迫的还是网站交互、体验、样式上的优化哦

**Comment by ghost** [comment]
别搞React，背离标准，很快就会被替代，如 Polymer.

**Comment by chpengzh** [comment]
@kriry react 怎么就背离标准了啊，话说标准是什么啊，后端mvc还是前端mvc还是还是别的啊，连[dockerhub](https://hub.docker.com/)这种网站都是用的react啊

**Comment by MiYogurt** [comment]
根本就没什么标准，每一项事物的出现就是为了解决某一方面的问题，只要能解决问题，不论是流行或者是不流行都行。  
当然老李觉得成本太高，也是一项该考虑的因素。  
因为对于一些新东西，我也不是很熟悉，经验也不多，做好的成本就更高了。

**Comment by liyuan462** [comment]
@MiYogurt 嗯，我不是说react不好，我个人比较喜欢的就是react，不过现在的关键问题是没有内容和人气，有个优先级，当然，如果react很牛，能把站做得很炫吸引很多人来，也是欢迎的，另外，现在想在论坛的基础上做一些其他的版块，比如招聘版块或wiki版块，可以用react做新的版块。

**Comment by liyuan462** [comment]
@chpengzh 是吗？我还没发现dockerhub是用react写的。。。

**Comment by chpengzh** [comment]
@liyuan462 遇到好看的页面总有打开控制台看一眼的冲动
