### ISSUE TITLE
期望加上 RSS 订阅功能

### ISSUE THREAD

**Issue by chpengzh** [rust-cn/rust_lang_cn#8]
作为一个学习者可能跟希望能通过rss阅读器来订阅论坛下的最新文章

**Comment by liyuan462** [comment]
谢谢 @chpengzh 的建议，会加入工作计划

**Comment by liyuan462** [comment]
@chpengzh 已经加上对RSS的支持， =>https://github.com/rust-cn/rust_lang_cn/commit/bc80f496838ad76ea1556e1e44bbd0a78706bd11

**Comment by chpengzh** [comment]
好快！

**Comment by liyuan462** [comment]
@chpengzh 你如果对Rust有兴趣的话也欢迎参与开发哦
